
service: api
frameworkVersion: "3"

plugins:
  - serverless-plugin-typescript

provider:
  name: aws
  httpApi:
    authorizers:
      authorizer:
        type: request
        functionName: authorizer
  runtime: nodejs16.x


  stage: dev
  region: us-east-1

functions:
  register:
    role: ${ssm:${self:custom.stage}-register-iam-role}
    handler: register/handler.register
    environment:
      DYNAMODB_USERS: ${ssm:${self:custom.stage}-dynamodb-users-table}
    events:
      - httpApi:
          path: /users
          method: post

  login:
    role: ${ssm:${self:custom.stage}-login-iam-role}
    handler: login/handler.login
    environment:
      DYNAMODB_USERS: ${ssm:${self:custom.stage}-dynamodb-users-table}
      JWT_SECRET: ${ssm:${self:custom.stage}-jwt-secret}
      EMAIL_GSI: ${ssm:${self:custom.stage}-email-gsi}
    events:
      - httpApi:
          path: /login
          method: post

  create_booking:
    role: ${ssm:${self:custom.stage}-create-booking-iam-role}
    handler: create-booking/handler.create
    environment:
      DYNAMODB_BOOKINGS: ${ssm:${self:custom.stage}-dynamodb-bookings-table}
    events:
      - httpApi:
          path: /bookings
          method: post
          authorizer: authorizer

  authorizer:
    handler: authorizer/handler.authorizer
    environment:
      JWT_SECRET: ${ssm:${self:custom.stage}-jwt-secret}
          
custom:
  stage: ${opt:stage, self:provider.stage}